version: "3.6"

services:

  segmentation_api:
    build: ./           # 指向相关镜像的Dockerfile所在目录
    container_name: segmentation_api
    restart: always
    environment:             # 配置容器的环境变量
      - APP_NAME=SA
#    expose:                  # 将该容器的5000端口开放给同一网络下的其他容器和服务
#      - 5000
    ports:                   # HOST:CONTAINER 将主机的80端口映射到容器的80端口，相当于将nginx容器的80端口开放给外部网络
      - 5050:5050
    volumes:
      - ./:/app